### ISSUE TITLE
[Issue]: FailedNotifications NullPointerException

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#137] opened 2023-11-23 09:11 UTC
### Describe the Issue

We are seeing regular null pointer exceptions on our UAT environment from the FailedNotificationService:

> org.quartz.core.JobRunShell - Job DEFAULT.NotificationProcessJob threw an unhandled Exception: 
java.lang.NullPointerException: Cannot invoke "com.paypal.infrastructure.hyperwallet.configuration.HyperwalletProgramsConfiguration$HyperwalletProgramConfiguration.getUsersProgramToken()" because "programConfiguration" is null
	at com.paypal.infrastructure.hyperwallet.services.UserHyperwalletSDKServiceImpl.getProgramToken(UserHyperwalletSDKServiceImpl.java:20)
	at com.paypal.infrastructure.hyperwallet.services.AbstractHyperwalletSDKService.getHyperwalletInstanceByHyperwalletProgram(AbstractHyperwalletSDKService.java:31)
	at com.paypal.notifications.failures.connectors.NotificationsRepositoryImpl.getHyperwalletWebhookNotification(NotificationsRepositoryImpl.java:28)
	at com.paypal.notifications.failures.services.FailedNotificationServiceImpl.getNotificationToReprocess(FailedNotificationServiceImpl.java:49)

`
	@Override
	public void processFailedNotifications() {
		final Iterable<NotificationInfoEntity> failedNotifications = failedNotificationInformationRepository.findAll();
		//@formatter:off
		StreamSupport.stream(failedNotifications.spliterator(), false)
				.map(this::getNotificationToReprocess)
				.filter(Objects::nonNull)
				.forEach(notificationProcessingService::processNotification);
		//@formatter:on
	}

	private HyperwalletWebhookNotification getNotificationToReprocess(
			final NotificationInfoEntity failedNotificationInformationEntity) {
		log.info("Reprocessing notification [{}]", failedNotificationInformationEntity.getNotificationToken());
		return notificationsRepository.getHyperwalletWebhookNotification(
				failedNotificationInformationEntity.getProgram(),
				failedNotificationInformationEntity.getNotificationToken());
	}
`
It would appear that the entity does not have a program stored against it?
Since it is an H2 running in exclusive mode - I can't inspect the database without stopping the instance.
I would also imagine this avoids the max retries counter since it errors before that.

Inspecting the webhook does show that it has a programToken:

 "programToken": xxxxxxxxxx

 "type": "USERS.UPDATED.VERIFICATION_STATUS.REQUIRED",

Checking NotificationToNotificationInfoConverter - seems :

`
if (notificationBody instanceof Map) {
			final Map<String, String> notificationDetails = (Map<String, String>) notificationBody;

			Optional.ofNullable(notificationDetails.get("token"))
					.ifPresent(notificationInfoEntityNotification::setTarget);
			Optional.ofNullable(notificationDetails.get("programToken"))
					.ifPresent(notificationInfoEntityNotification::setProgram);
		}
`
has been there since 02/2022!

Any suggestions on what we can do? (Assume we need to connect to db and inspect?

Thanks.
Russ

### Environment

Test/UAT

### Version

5.0.0

### Expected Behavior

Failed notification processes or warns can't be processed due to missing token?

### Actual Behavior

NullPointerException

### Steps to Reproduce

Not sure -> this is from a webhook from Hyperwallet

### Relevant log output

```shell
23-11-2023 08:30:00.004 [HyperwalletMiraklScheduler_Worker-6] ERROR  org.quartz.core.JobRunShell - Job DEFAULT.NotificationProcessJob threw an unhandled Exception: 
java.lang.NullPointerException: Cannot invoke "com.paypal.infrastructure.hyperwallet.configuration.HyperwalletProgramsConfiguration$HyperwalletProgramConfiguration.getUsersProgramToken()" because "programConfiguration" is null
	at com.paypal.infrastructure.hyperwallet.services.UserHyperwalletSDKServiceImpl.getProgramToken(UserHyperwalletSDKServiceImpl.java:20)
	at com.paypal.infrastructure.hyperwallet.services.AbstractHyperwalletSDKService.getHyperwalletInstanceByHyperwalletProgram(AbstractHyperwalletSDKService.java:31)
	at com.paypal.notifications.failures.connectors.NotificationsRepositoryImpl.getHyperwalletWebhookNotification(NotificationsRepositoryImpl.java:28)
	at com.paypal.notifications.failures.services.FailedNotificationServiceImpl.getNotificationToReprocess(FailedNotificationServiceImpl.java:49)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.paypal.notifications.failures.services.FailedNotificationServiceImpl.processFailedNotifications(FailedNotificationServiceImpl.java:42)
	at com.paypal.notifications.failures.jobs.NotificationProcessJob.execute(NotificationProcessJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by jluisalias-e2y** [comment] 2023-11-28 17:27
Hi @RussGarratt , how are you doing? 'd say that the issue may be related to some kind of misconfiguration with the programs' configuration between Mirakl and Hyperwallet in UAT. So, when the job tries to process the failed notifications (FailedNotificationServiceImpl.java line 40), it gets the program from the notification in line 50: 
`
        private HyperwalletWebhookNotification getNotificationToReprocess(
			final NotificationInfoEntity failedNotificationInformationEntity) {
		log.info("Reprocessing notification [{}]", failedNotificationInformationEntity.getNotificationToken());
		return notificationsRepository.getHyperwalletWebhookNotification(
				failedNotificationInformationEntity.getProgram(),
				failedNotificationInformationEntity.getNotificationToken());
	}
`
Then it looks for that program in the Hyperwallet-defined programs, it does it through HyperwalletProgramsConfiguration.java line 41:
`
        public HyperwalletProgramConfiguration getProgramConfiguration(final String programName) {
		return programTokensMap.get(programName);
	}
`
That Map is built and filled by: 
`
        private void buildProgramTokensMap() {
		//@formatter:off
		try {
			programTokensMap = IntStream.range(0, hyperwalletProgramsNames.size())
					.mapToObj(i -> new HyperwalletProgramConfiguration(hyperwalletProgramsNames.get(i),
							ignoredHyperwalletPrograms.contains(hyperwalletProgramsNames.get(i)),
							hyperwalletUserProgramTokens.get(i),
							hyperwalletPaymentProgramTokens.get(i),
							hyperwalletBankAccountTokens.get(i)))
					.collect(Collectors.toMap(HyperwalletProgramConfiguration::getProgramName, Function.identity()));
		}
		catch (final Exception e) {
			throw new InvalidConfigurationException("Property files configuration error. Check Hyperwallet program tokens configuration.", e);
		}
		//@formatter:on
	}
`

Where hyperwalletUserProgramTokens comes from Hyperwallet configuration, is it possible to check those values to see if everything is okay between the two systems? could you please provide me the info of which environment URL are you working on, and I'll try to check those? 

Thanks!

**Comment by RussGarratt** [comment] 2024-02-01 15:09
@jluisalias-e2y 

Sorry for the late reply on this one, we believe this may be linked to the 5.0.0 upgrade.

What we are seeing:
we have an entry in : notification_info_entity

Where:  program is actually the program ID (not default) e.g. prg-xxxxxx-xxx-xxx

The notification process retry job loads this out of the Notifications Repositry, and calls:

```
(HyperwalletProgramsConfiguration.java)
	public HyperwalletProgramConfiguration getProgramConfiguration(final String programName) {
		return programTokensMap.get(programName);
	}
```

```
private void buildProgramTokensMap() {
		//@formatter:off
		try {
			programTokensMap = IntStream.range(0, hyperwalletProgramsNames.size())
					.mapToObj(i -> new HyperwalletProgramConfiguration(hyperwalletProgramsNames.get(i),
							ignoredHyperwalletPrograms.contains(hyperwalletProgramsNames.get(i)),
							hyperwalletUserProgramTokens.get(i),
							hyperwalletPaymentProgramTokens.get(i),
							hyperwalletBankAccountTokens.get(i)))
					.collect(Collectors.toMap(HyperwalletProgramConfiguration::getProgramName, Function.identity()));
		}
		catch (final Exception e) {
			throw new InvalidConfigurationException("Property files configuration error. Check hyperwallet program tokens configuration.", e);
		}
		//@formatter:on
	}
```


So what we see is that the map is built like:  
key:  DEFAULT  value: prg-XXXXX

but the failed notification is saved as prg-token

I would imagine this is a bug after the addition of the multi program support?

Probably need to consider:  AbstractNotificationListener.java also - > where the failed notifications are saved?

Regards,
Russ

**Comment by RussGarratt** [comment] 2024-02-01 15:11
![Uploading Program_Token.png…]()

**Comment by Magdoosha** [comment] 2024-02-07 09:19
Hi @RussGarratt We are looking into this and will let you know. Thanks

**Comment by smaxx** [comment] 2024-02-07 15:34
we have recently faced the same issue. After some investigation we can see the root cause as invalid usage of "program" vs  "programToken". When a webhook notification fails, the details are stored to notification_info_entity table, and our attention point is "program" column, but from the tests in the repository we can see that actually it is expected to have programToken(see NotificationToNotificationInfoConverterTest:77):
```
assertThat(result.getProgram()).isEqualTo(PROGRAM_TOKEN);
```
And we can see the program token value in actual DB records.

Later on when there is an attempt to replay the notification the following code is executed(see NotificationsRepositoryImpl:27):
```
final Hyperwallet hyperwalletInstance = userHyperwalletSDKService
				.getHyperwalletInstanceByHyperwalletProgram(program);
```
So as you can see the naming-related confusion happens and we're trying to get a Hyperwallet instance by program name while "programToken" is actually passed as a parameter as it is taken from the persisted NotificationInfoEntity#program property and we already know that it actually holds the token, not program name.

The issue can be easily fixed by simply adjusting the last line to:
```
public HyperwalletWebhookNotification getHyperwalletWebhookNotification(final String programToken, final String token) {
		final Hyperwallet hyperwalletInstance = userHyperwalletSDKService
				.getHyperwalletInstanceByProgramToken(programToken);
```

**Comment by Magdoosha** [comment] 2024-02-07 15:42
Thanks @smaxx We are looking into this and will respond to your comments in due course. Thank you for your insight.

**Comment by adbame** [comment] 2024-02-08 16:29
Hi @smaxx 

Thanks for your contribution
We are on it

**Closed** 2024-03-19 12:07 UTC
