### ISSUE TITLE
[Issue]: Seller Accounts not syncing to Production

### ISSUE THREAD

**Issue by pradeep-agnihotri** [paypal/mirakl-hyperwallet-connector#101] opened 2022-10-26 16:29 UTC
### Describe the Issue

During the SellerSync process, the Seller accounts from Production Mirakl are not getting synced into Production HyperWallet.
The process is able to pick the Seller Account from Mirakl, however logs show errors, a few listed below, and does not create the HyperWallet Account.

- Shops retrieved [2002] 
- SellersTokenSynchronizationServiceImpl : Error while getting Hyperwallet user by clientUserId [2002] 
- com.hyperwallet.clientsdk.HyperwalletException: The information entered does not match our records. Please try again.
- No bank account info for shop code: [2002]
- Failed processing item of type ProfessionalSeller with id: 2002

We have verified that the HWC environment variables are set to connect to the production instance of HyperWallet and Bank Account details are present for the Seller Account.
Note that in HyperWallet Production, we do have one single account manually created with a different ID, that does not exist in Mirakl.
The detailed logs are attached.

Can you please review and guide on what could be the reasons for account not syncing into HyperWallet.

### Environment

Live/Production

### Version

4.14.0

### Expected Behavior

The Seller Account when created/updated in Mirakl should sync into HyperWallet portal.

### Actual Behavior

The Seller Account when created/updated in Mirakl do not sync to HyperWallet reporting that Seller information does not match.

### Steps to Reproduce

1. Create a new Seller Account and ensure all required fields are populated.
2. Alternatively update an existing account.
3. Validate that the sync job executes, by validating log output.
4. Observe that logs report that Seller Account was not synced.
5. Observe in HyperWallet portal that Seller account was not created.

### Pre-conditions

- In HyperWallet an account has been previously created manually.
- HypewWallet Connect app is installed and sync jobs are executing.

**Comment by pradeep-agnihotri** [comment] 2022-10-26 16:30
Logs
[hwc_logs_20221025-01.txt](https://github.com/paypal/mirakl-hyperwallet-connector/files/9871663/hwc_logs_20221025-01.txt)

**Comment by max6001** [comment] 2022-10-27 15:06
Hi @pradeep-agnihotri and thanks for reaching out.

When pulling a shop from Mirakl, the SellerExtractJob checks if that shop already exists in Hyperwallet before creating it by using https://docs.hyperwallet.com/content/api/v4/resources/users/list

It seems this API call is currently failing with:
`SellersTokenSynchronizationServiceImpl : Error while getting Hyperwallet user by clientUserId [2002]`
`com.hyperwallet.clientsdk.HyperwalletException: The information entered does not match our records. Please try again.`

When calling this Hyperwallet API, the HMC Is sending two values:
- clientUserId (= the mirakl shop id)
- programToken (= PAYPAL_HYPERWALLET_PROGRAM_ TOKEN_USERS_DEFAULT value)

As described in our documentation https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/4.17.0/readme/readme.html#_configuration:

PAYPAL_HYPERWALLET_PROGRAM_ TOKEN_USERS_DEFAULT
The program token for contacting the Hyperwallet API on the /users path for DEFAULT program.

It's very likely that the issue is coming from the value you've set in your configuration file that doesn't match the one on Hyperwallet side. I would recommend to double check it.

If the issue persists, we will need the full API call body either from your server logs or from Hyperwallet support team.

**Comment by pradeep-agnihotri** [comment] 2022-10-27 18:40
Hello @max6001 ,
We had already verified the Program_Token_Users with the the HyperWallet API "/rest/v4/users" and validated it returns the existing Users from HyperWallet. Currently there is no Seller account created in HyperWallet, only the Millipore Account has been added as Operator.
The API HyperWallet API "/rest/v4/users" returns that single account and that would not match with the ClientUserId=2002.

Would you be reaching to HyperWallet Support team for getting access to the logs?
Is there any additional information we can provide from our end to identify the root cause?

Thank you.

**Comment by max6001** [comment] 2022-10-27 21:10
Hi @pradeep-agnihotri 

If I understand correctly you tried calling the /rest/v4/users outside of the HMC and it worked fine which is already a good indicator.
I'm a bit confused by your statement saying:
- " validated it returns the existing Users from HyperWallet"
- "Currently there is no Seller account created in HyperWallet"

I might be mistaken but a user in HW = a shop in Mirakl, no?

If the API worked fine outside of the HMC it confirms your program token users default value is correct. Now, we need to understand what HW is receiving from the HMC so it triggers this error.
Only solutions are:
- You check your server logs and see the API request being sent
- You contact hyperwallet prod support to see if they can provide you the API content

Let us kn,ow how that goes,

**Comment by kshunt-paypal** [comment] 2022-10-28 21:14
@max6001 please see attached log of all API calls the Production Support team found for Millipore's Production Hyperwallet program. It doesn't appear we've received any POST calls, only GET. 

[PROD REST API Calls - MilliporeSigma - August to October 28, 2022.xlsx](https://github.com/paypal/mirakl-hyperwallet-connector/files/9891887/PROD.REST.API.Calls.-.MilliporeSigma.-.August.to.October.28.2022.xlsx)

**Comment by max6001** [comment] 2022-10-28 21:16
Hi @kshunt-paypal 

Is there a way to see the API call body?
Technically there shouldn't be any response because the SDK crashed/returned an error but I'm wondering if the call reached HW and if we could see it's content aka the parameters and values sent when calling /rest/v4/users

**Comment by pradeep-agnihotri** [comment] 2022-10-28 22:36
Hello @max6001 
Looking at the API calls from the logs, the requests are getting to Hyperwallet and HyperWallet is returning the User and the associated bank information that is stored in HyperWallet. 
As I had noted, the User was created directly in HyperWallet and this User Account is not a Seller Account in Mirakl. Is that resulting into that error? 
Is the Connector trying to match the record from HyperWallet with Mirakl, as that HyperWallet only account is not present in Mirakl.

Thanks,
Pradeep.

**Comment by max6001** [comment] 2022-10-28 23:49
Hi Pradeep,

> Looking at the API calls from the logs, the requests are getting to Hyperwallet and HyperWallet is returning the User and the associated bank information that is stored in HyperWallet.

I'm not sure to follow you here. If that was happening so successfully then why the Hyperwallet SDK would throw errors such as
```
SellersTokenSynchronizationServiceImpl : Error while getting Hyperwallet user by clientUserId [2002]
com.hyperwallet.clientsdk.HyperwalletException: The information entered does not match our records. Please try again.
```
From our initial thinking the API requests is being built by the HMC then the HMC tries to send the request but the Hyperwallet is returning that error. Not sure yet if that error is returned BEFORE sending the API request to Hyperwallet or after (most likely it would be after) which is why we would need the content of that API request sent by the HMC (only way to get it would be to analyse your network traffic and catch the request or have Hyperwallet support team check if they can find those requests who shouldn't appear as succesful.

> As I had noted, the User was created directly in HyperWallet and this User Account is not a Seller Account in Mirakl. Is that resulting into that error?

As long as you haven't used the same ID in Hyperwallet as the shop ID created in Mirakl we normally wouldn't care.

> Is the Connector trying to match the record from HyperWallet with Mirakl, as that HyperWallet only account is not present in Mirakl.

Nop. The HMC will only push data from Mirakl to HW and care only of HW feedbacks regarding the items pushed. Any item created on Hyperwallet outside of the HMC wouldn't be taken into account by the HMC.

**Comment by pradeep-agnihotri** [comment] 2022-10-31 21:15
@kshunt-paypal 
Can you please assist with providing the request body that was being received on HyperWallet side.

@max6001 
Please see below response to your commets;
> I'm not sure to follow you here. If that was happening so successfully then why the Hyperwallet SDK would throw errors such as
That error seems to be generating from within HWConnector App. This is where we need your/your team assistance to identify the reason. The ClientUserId "2002" mentioned in the error is the one present in MIrakl and there is no corresponding HW account in HyperWallet. HyperWallet only contains one single HW account which belongs to Millipore and has a different ClientUserId. If we see the response in the logs shared by HyperWallet team, we see that it is returning the HW Account.

**Comment by kshunt-paypal** [comment] 2022-10-31 22:15
@max6001 @pradeep-agnihotri - given the only API calls we've seen from Millipore in Prod are GET calls, there is no body beyond the details provided last week. GET calls are just asking to retrieve data from the HW system, so the Production Support team provided everything that was included.

**Comment by pradeep-agnihotri** [comment] 2022-11-02 13:42
@max6001 
As @kshunt-paypal , has mentioned all the API request had been GET request hence there is no body and there has been no POST request. 
What are the next steps here to identify the cause? 

Thank you.

**Comment by max6001** [comment] 2022-11-02 13:51
Hi @pradeep-agnihotri sorry for the delay as yesterday was a bank holiday in France and Spain.
We've reviewed our code and it seems we are only passing the shop ID to the HW SDK in order to call the GET user API.
That shop ID should be retreived by the HMC and Mirakl and we don't quite understand why it would create any issue.

To put it simply:
- The HMC calls the Mirakl API to retrieve all the shops to process
- For each shops the HMC is calling the HW API (using the SDK) to check if that shops already exists.

Looking at the logs again:
- The HMC did manage to retrive shop 2002
- For shop 2002 the HMC is calling the HW API (using the SDK) and we get the following response:
> SellersTokenSynchronizationServiceImpl : Error while getting Hyperwallet user by clientUserId [2002]
> com.hyperwallet.clientsdk.HyperwalletException: The information entered does not match our records. Please try again.

@kshunt-paypal I'm gonna need your HW expertise on this. What exactly `The information entered does not match our records` means? We want to understand the use case where HW SDK would throw that error to guide us in our investigation.

**Comment by kshunt-paypal** [comment] 2022-11-03 19:07
@max6001 @pradeep-agnihotri the Production Support team was able to confirm that the message referred to in Max's comment yesterday is due to incoming GET calls from an IP that was not previously approved. We have now added that IP address to the approved list, so this error should be resolved. That being said, we're still only seeing GET calls across all of the approved IPs, with no record of POST calls to do things like create a user and register a transfer method. 

@pradeep-agnihotri - can you please email me a list of all possible IPs we could receive calls from for your program? We currently only have three, including the one we've just added to the list based on this discovery. This way we can avoid any future instances of this same error should there be other IPs in the mix.

**Comment by pradeep-agnihotri** [comment] 2022-11-04 15:09
Hello @kshunt-paypal 
I have confirmed with the DevOps and Cloud team, the IP Address has not changed and remains the same. I will share the IP address over the email.

**Comment by max6001** [comment] 2022-11-07 11:27
@pradeep-agnihotri have you been able to successfully create a payee within Hyperwallet since the IP addresses got whitelisted?

Please keep us posted.

**Comment by pradeep-agnihotri** [comment] 2022-11-07 16:50
@max6001 
The seller sync has started working, but now the process is failing on the bank sync throwing error;
b.c.i.m.MiraklToBankAccountModelExecutor : No bank account info for shop code: [xxxx] 

We have verified that bank account information does exist for these Sellers in Mirakl. 

@kshunt-paypal 
Can you please reach to your technical team for logs around the Bank information sync, that you help in further debugging.

**Comment by kshunt-paypal** [comment] 2022-11-07 18:57
@pradeep-agnihotri we do see that there have been a couple of seller profiles successfully created on our end (one on Friday 11/4 and one today). We do not see any attempts to add a bank account to those profiles when reviewing the API logs across the three IP addresses you've provided. Do you have a timestamp for any of those attempts that you can share with us, so that we can narrow our search?

**Comment by pradeep-agnihotri** [comment] 2022-11-07 22:45
@kshunt-paypal 
attached are the logs that list the timestamps.

@max6001 
based on the feedback from @kshunt-paypal , looks like the requests may not be originating to HyperWallet. 
We are observing that the following warning is added to the logs; are there any cases where the bank account details are matched with the Seller accounts. Please see the attached log file for more logs. 
[hwc_logs_20221107-03.txt](https://github.com/paypal/mirakl-hyperwallet-connector/files/9956084/hwc_logs_20221107-03.txt)

`No bank account info for shop code: [2000]`

We have validated the following fields have been setup for the bank account information;
1. Bank account owner name
2. Bank name
3. Bank address
4. Bank Zip Code/Postal code
5. Bank City/Town
6. Bank Account State/Province
7. Bank Account Number
8. Routing Number (ABA)
9. BIC

Are we missing any fields for Bank ?

Thank you.

**Comment by max6001** [comment] 2022-11-07 23:05
@pradeep-agnihotri to keep track I'm going to close this issue (related to the incapacity of creating shops) and will ask you to open a new one for the bank account problem.

I thank you for your understanding.

Best,

**Closed by max6001** 2022-11-07 23:05 UTC
