### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#132] opened 2023-08-21 13:51 UTC
Hi team,

Please can you let me know whether there are any plans to be able to individually disable health checks in version 5.x?

We still have an issue with the HyperwalletApiHealthCheck.

The H2 database in embedded mode:

* Only allows a single JVM instance, so we cannot do blue / green deployments.
* In AWS using EKS -> the health and info checks must pass in order for the pod to be marked active and endpoints to work
* The hyperwallet health check -> will fail if Paypal is configured with a Jkwset URL (on your connector) (chicken and egg) as the /jwkset url is not accessible until the health check passes.

`	@Override
	public HyperwalletAPICheck check() {
		if (startupChecksEnabled) {

			try {
				final HyperwalletProgram hyperwalletProgram = hyperwalletAPIHealthCheckConnector.getProgram();
				return hyperwalletAPIHealthCheckConnectorConverter.from(hyperwalletProgram);
			}
			catch (final Exception e) {
				return hyperwalletAPIHealthCheckConnectorConverter.from(e);
			}
		}
		else {
			return HyperwalletAPICheck.builder().hyperwalletAPICheckStatus(UP).location("http://null")
					.error("Disabled via config").build();
		}
	}`

Thanks and regards,
Russ

**Comment by javierpoloe2y** [comment] 2023-09-05 07:41
Hi @RussGarratt,

I understand that the startup check fails, since the context is not ready yet, and the `/jwkset` endpoint is unavailable. But when the "/health" endpoint is available after the context has been initialized, the `/jwkset` endpoint should also be available, and the health check should pass.

Is the health check failing after the application is started?

Regarding your question about disabling health checks, if possible, we would prefer to make them work in all scenarios before giving the option to disable them because they are failing.

**Comment by RussGarratt** [comment] 2023-09-06 07:45
hi @javierpoloe2y 

I think the issue is largely with the fact that we are using the .h2 database in exclusive mode. So you can only ever have 1 JVM running.

So to deploy, the previous version/instance has to be shut down completely to allow another instance to start using the database.

Old Pod (vers 4.X) -> Complete Shutdown  (/jwkset unavailable)
New Pod -> Start Up  (health check fail) -> never brought into live state/added into loadbalancer as a usable pod for health to pass

K8s are set to be configured to bring instance into live state once health (liveness and readiness) checks pass.

So we get stuck in this place.
A rollback suffers the same in reverse too (can't rollback to ver 4.X for same reason) -> startup, fail health, not marked as live in loadbalancer.

Hope that helps?

Regards,
Russ

**Comment by javierpoloe2y** [comment] 2023-09-06 14:33
Hi @RussGarratt,

You are correct, the connector doesn't support more than one instance running simultaneously. The problem is not only the usage of an embedded database, but the connector doesn't coordinates the scheduling and execution of jobs across multiple instances.

I think that I understand your problem, since the health check fails, Kubernetes is not routing the traffic to that pod so the `/jwkset` endpoint never gets reachable.

As a solution perhaps you can serve the public JWK key set as a static resource from another service or from S3 and configure Hyperwallet so it takes the public keys from that URL. By doing this, the availability of the keys is not tied to the pod lifecycle so the health. check should pass.

Initially the `/jwkset` endpoint was added to simplify the deployment process so you don't need any additional infrastructure components to serve the keys, but you aren't forced to rely on it. (there is a short mention to this at the end of the [encryption configuration guide](https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/configuration/encryption/encryption.html))

I hope this works for you.

**Comment by monti-star** [comment] 2023-09-11 22:50
Are there any further actions necessary on this ticket? Otherwise we will close this issue by the end of the week.

**Comment by RussGarratt** [comment] 2023-09-14 08:38
Thanks @javierpoloe2y  and @devchristina 
I think moving the pub keys to a static location is probably the best option.

Will add to our backlog.
Happy to close ticket,

Best regards,
Russ

**Comment by devchristina** [comment] 2023-09-14 13:50
@RussGarratt that is fair feedback. Thank you!

**Closed by devchristina** 2023-09-14 13:50 UTC
Labels: question
